WinWaitActive("Open","",10)
ControlFocus("Open","","Edit1")
Sleep(2000)
ControlSetText("Open","","Edit1","C:\Neha\Automation_Stuff\Automation Framework_Kiran\Wrap Portal\AutoIT Script\Neha.pdf")
ControlClick("Open","","Button1")